# Generated by Django 4.0.3 on 2022-03-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petstagramuser',
            options={'permissions': ()},
        ),
    ]
