# Generated by Django 4.0.3 on 2022-03-31 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_petstagramuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petstagramuser',
            options={'permissions': (('can_go_in_non_ac_bus', 'To provide non-AC Bus facility'), ('can_go_in_ac_bus', 'To provide AC-Bus facility'), ('can_stay_ac-room', 'To provide staying at AC room'), ('can_stay_ac-room2', 'To provide staying at Non-AC room'), ('can_go_dehradoon', 'Trip to Dehradoon'), ('can_go_mussoorie', 'Trip to Mussoorie'), ('can_go_haridwaar', 'Trip to Haridwaar'), ('can_go_rishikesh', 'Trip to Rishikesh'))},
        ),
    ]
