# Generated by Django 4.0.3 on 2022-03-31 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_petstagramuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petstagramuser',
            options={},
        ),
    ]
