# Generated by Django 4.0.3 on 2022-03-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_completedorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedOrder',
        ),
    ]
